app:
    resource: "@AppBundle/Controller/"
    type:     annotation

test:
    path:   /test
    defaults: { _controller: AppBundle:Default:test }

homepage:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

register:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }
