app:
    resource: "@AppBundle/Controller/"
    type:     annotation

test:
    path:   /test
    defaults: { _controller: AppBundle:Default:test }

homepage:
    path:     /
    defaults: { _controller: AppBundle:Interest:index }

register:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

edit_interest:
    path: /interest/edit/{id}
    defaults: { _controller: AppBundle:Interest:edit }

upload:
    path: /upload/{what}
    defaults: { _controller: AppBundle:Default:upload }

upload_reverse:
    path:    /upload-reverse/{what}
    defaults: { _controller: App:Default:uploadReverse }
